### ISSUE TITLE
Test server on timeweb

### ISSUE THREAD

**Issue by flancer64** [flancer32/pwa-ra-base#30]
заказ тестового сервера на timeweb'е.

**Comment by flancer64** [comment]
@minkinr , не вижу возможности сделать отдельную ссылку на конфигурацию. В общем, нам нужен "Облачный сервер" вот с такой конечной конфигурацией:

![Image](https://user-images.githubusercontent.com/5052385/197547626-ebf833a3-92e6-4c09-a56d-ee3e590460e7.png)

Если есть возможность изменить параметры выбранного сервера, то было бы хорошо добавить ещё 2 Гб оперативной памяти (итого: 4 Гб). И тут не нужны ежедневные backup'ы (они автоматом добавляются, нужно снять выделение):

![Image](https://user-images.githubusercontent.com/5052385/197548249-77d64dba-fe83-46e8-bc88-81c93f4f78b4.png)

**Comment by minkinr** [comment]
Сделала TEST Rehapp
CPU 3,3 ггц ( 2,4  не получилось) 

https://vds.timeweb.ru/servers/1079107

![image](https://user-images.githubusercontent.com/103753072/197759694-861d5af2-d151-49c6-b885-e5ea67f548b5.png)

**Comment by minkinr** [comment]
4 гб тоже не поняла где сделать

**Comment by flancer64** [comment]
@minkinr , у них есть возможность изменить конфигурацию виртуального сервера:
![image](https://user-images.githubusercontent.com/5052385/197772451-de34706f-2375-4ea6-aaea-70258345175c.png)

Но нам пока что и этой конфигурации хватит. Кастомная конфигурация получается дороже, чем то, что у них в Premium NVMe идёт, а нам чисто "для поиграться".

**Comment by flancer64** [comment]
Вошёл на сервер как root по своему ssh-ключу.
